### ISSUE TITLE
make sure report download links are right

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#67]
- [x] create pdfs for downloading executive summaries
- [ ] update lis report download links

**Comment by sssoz** [comment]
Just added the full-report PDFs for Landscape Analysis & Roadmap for Action. 

- They are stored in `media/pdf/`
- Report HTML pages are now in `report/`
- Each PDF must be named after its corresponding report page (`report-[hyphenated-report-title-slug]`)
- To display a report’s full PDF, change the `pdf: false` variable to `true` in the report page

**Comment by ssssoz** [comment]
Just added the full-report PDFs for Landscape Analysis & Roadmap for Action. 

- They are stored in `media/pdf/`
- Single report pages are now in `reports/`
- Single topic-based thread pages are now in `topics/` 
- Each report & thread page is now in `.md` to allow the use of Markdown in the content (just in case you might need this in the future); it will be converted to HTML on build
- Each PDF must be named after its corresponding report page:`report-[hyphenated-report-title-slug]`
- To display a report’s full PDF, change the `pdf: false` variable to `true` in the report page’s frontmatter

**Comment by JosephMcArthur** [comment]
I don't understand why this is different:

> Single report pages are now in reports/
> Single topic-based thread pages are now in topics/

And, whole reports need to be downloaded from an external link (ideally set in front matter) when on report pages.

**Comment by ssssoz** [comment]
> I don't understand why this is different:
> 
> > Single report pages are now in reports/
> > Single topic-based thread pages are now in topics/

It was just a way to organise your files, but feel free to put them all in the same directory. Since you always determine the permalink for individual tag & topic pages, the directory name has no effect on the URL structure.

**Comment by JosephMcArthur** [comment]
OH. Sorry, this is about the files, not the PDFs. Of course. Sorry, I like this with the files.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
> And, whole reports need to be downloaded from an external link (ideally set in front matter) when on report pages.

It’s set to accept URLs now (external or internal). 

```yaml
---
layout: thread
title: Landscape Analysis
description: This report was commissioned in response to the growing trend of commercial acquisition of critical infrastructure in our institutions. It is intended to provide a comprehensive look at the current players in this arena, their strategies and potential actions, and the implications of these on the operations of our libraries and home institutions. It also outlines suggestions for an initial set of strategic responses for the community to evaluate in order to ensure it controls both this infrastructure and the data generated by/resident on it.
permalink: /landscape-analysis
reversed: true
pdf: "https://infrastructure.sparcopen.org/media/pdf/report-landscape-analysis.pdf"
date: 2019-03-29
---
```
